//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCursos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public Alumno(int id, string nombre, int idCurso, long nacimiento,
                      System.DateTime creacion, Curso curso)
        {
            this.id = id;
            this.nombre = nombre;
            this.idCurso = idCurso;
            this.creacion = creacion;
            this.Curso = curso;
        }
        public int id { get; set; }
        public string nombre { get; set; }
        public int idCurso { get; set; }
        public long nacimiento { get; set; }
        public System.DateTime creacion { get; set; }
    
        public virtual Curso Curso { get; set; }
    }
}
